#!/bin/sh
#volume_output=$(pactl get-sink-volume $(pactl info | grep 'Default Sink' | awk '{print $3}'))
#mute_status=$(pactl get-sink-mute $(pactl info | grep 'Default Sink' | awk '{print $3}') | awk '{print $2}')
volume=$(amixer get Master | awk -F"[][]" '/Left:/ {print $2}' | tr -d '%')
mute_status=$(amixer get Master | awk -F"[][]" '/Left:/ {print $4}')


if [ "$mute_status" == "off" ]; then
  echo -1  # return -1 if muted
else
  # extract the volume percentage (remove trailing %)
  #volume=$(echo "$volume_output" | awk '{print $5}' | tr -d '%')
  echo $volume
fi
