#!/bin/sh
i3-msg -t subscribe -m '{"type":"workspace"}' |
while read -r _; do
    workspaces_info=$(i3-msg -t get_workspaces)
    active_workspaces=$(echo "$workspaces_info" | jq --unbuffered -r -c '[.[] | {(.name): if .focused then "focused-workspace" elif .urgent then "urgent-workspace" else "active-workspace" end}] | add')
    echo "$active_workspaces"
done

