#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# keybindings daemon
sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &

#set keyboard
kb=$(lsusb | grep 'SHARKOON .* Keyboard')
if [ ${#kb[0]} -gt 0 ]; then
    setxkbmap -layout us -variant altgr-intl #-option compose:ralt
else
    setxkbmap -layout br -variant nodeadkeys -option compose:ralt
fi

# diversity of apps to start
nm-applet &
xfce4-power-manager &
numlockx on &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
conky -c ~/.config/leftwm/system-overview &
playerctld daemon &
$SCRIPTPATH/scripts/musiquinha-reborn/hook/build/musiquinha-reborn &
xss-lock --transfer-sleep-lock -- lock &
nitrogen --restore &
#insync start &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/leftwm/themes/current/picom.conf &> /dev/null &
fi

# Set the theme.ron config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

#mainbar
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &> /dev/null &
  index=$((index + 1))
done
